services:
  appointment:
    image: node
    volumes:
      - '../sharedine-appointment:/app/sharedine-appointment'
    working_dir: /app/sharedine-appointment/
    ports:
      - "3002:3002"
    command: > 
      bash -c
      "npm install
      && npm run start"

  user:
    image: node
    volumes:
      - '../sharedine-user:/app/sharedine-user'
    working_dir: /app/sharedine-user/
    ports:
      - "3001:3001"
    command: > 
      bash -c
      "npm install
      && npm run start"
      
  friends:
    image: node
    volumes:
      - '../sharedine-friends:/app/sharedine-friends'
    working_dir: /app/sharedine-friends/
    ports:
      - "3003:3003"
    command: > 
      bash -c
      "npm install
      && npm run start"

  chat:
    image: node
    volumes:
      - '../sharedine-chat:/app/sharedine-chat'
    working_dir: /app/sharedine-chat/
    ports:
      - "3004:3004"
    command: > 
      bash -c
      "npm install
      && npm run start"

  notifications:
    image: node
    volumes:
      - '../sharedine-notifications:/app/sharedine-notifications'
    working_dir: /app/sharedine-notifications/
    ports:
      - "3005:3005"
    command: > 
      bash -c
      "npm install
      && npm run start"