# Version is deprecated
# Compose stack name
name: sharedine

services:
  frontend:
    build: ./
    volumes:
      - ./:/app/
    command: > 
      bash -c
      "npm install
      && npm start"

  appointment:
    build: ../sharedine-appointment
    volumes:
      - ../sharedine-appointment/:/app/
    depends_on:
      - user
    command: > 
      bash -c
      "npm install
      && npm start"

  chat:
    build: ../sharedine-chat
    volumes:
      - ../sharedine-chat/:/app/
    depends_on:
      - user
    command: > 
      bash -c
      "npm install
      && npm start"

  contact:
    build: ../sharedine-contact
    volumes:
      - ../sharedine-contact/:/app/
    command: > 
      bash -c
      "npm install
      && npm start"

  payment:
    build: ../sharedine-payment
    volumes:
      - ../sharedine-payment/:/app/
    depends_on:
      - user
    command: > 
      bash -c
      "npm install
      && npm start"

  user:
    build: ../sharedine-user
    volumes:
      - ../sharedine-user/:/app/
    command: > 
      bash -c
      "npm install
      && npm start"

# TODO: Figure out Supabase integration