services:
  appointment:
    image: node
    volumes:
      - '../sharedine-appointment:/app/sharedine-appointment'
    working_dir: /app/sharedine-appointment/
    ports:
      - "3002:3002"
    command: > 
      bash -c
      "npm install
      && npm run start"

  user:
    image: node
    volumes:
      - '../sharedine-user:/app/sharedine-user'
    working_dir: /app/sharedine-user/
    ports:
      - "3001:3001"
    command: > 
      bash -c
      "npm install
      && npm run start"